# Generated by Django 4.0.6 on 2022-11-30 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_requirements_points_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.IntegerField(null=True)),
                ('thembnail', models.ImageField(null=True, upload_to='photos/%y/%m/%d')),
                ('title', models.CharField(max_length=100)),
                ('video_id', models.CharField(max_length=200)),
                ('time_der', models.FloatField(default=True)),
                ('is_preview', models.BooleanField(default=False)),
                ('Lesson_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.lesson')),
                ('course_Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.course')),
            ],
        ),
    ]
