# Generated by Django 4.0.6 on 2022-11-30 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_lesson_name_video_lesson'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='Lesson',
            new_name='lesson',
        ),
    ]
