# Generated by Django 4.0.6 on 2022-11-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_lesson_video_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time_der',
            field=models.IntegerField(default=True),
        ),
    ]
