# Generated by Django 4.0.6 on 2022-11-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_video_time_der'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='Special',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
