# Generated by Django 4.0.6 on 2022-11-30 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_author_special'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='course_Name',
            new_name='course',
        ),
    ]
