# Generated by Django 4.0.6 on 2022-11-30 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_course_name_video_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='Special',
            new_name='special',
        ),
    ]
