# Generated by Django 4.0.6 on 2022-11-30 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_special_author_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languoge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languoge', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='languoge',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='app.languoge'),
            preserve_default=False,
        ),
    ]
