# Generated by Django 4.0.6 on 2022-11-30 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_languoge_course_languoge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='languoge',
        ),
    ]
