# Generated by Django 4.0.6 on 2022-11-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_course_languoge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languoge',
            name='languoge',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
