# Generated by Django 4.0.6 on 2022-11-30 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_languoge_languoge'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Languoge',
        ),
    ]
