# Generated by Django 4.0.6 on 2022-11-30 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_delete_languoge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languoge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languoge', models.CharField(max_length=30)),
            ],
        ),
    ]
