# Generated by Django 4.0.6 on 2022-11-30 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_languoge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Languoge',
            new_name='Aanguoge',
        ),
    ]
