# Generated by Django 4.0.6 on 2022-11-30 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_rename_languoge_aanguoge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aanguoge',
            new_name='Languoge',
        ),
    ]
