# Generated by Django 4.0.6 on 2022-11-30 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_rename_aanguoge_languoge'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='languoge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.languoge'),
        ),
    ]
