# Generated by Django 4.0.6 on 2022-11-30 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_course_deadline_alter_video_lesson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Deadline',
        ),
    ]
